# FIX A: ОТКЛЮЧЕНИЕ MOSAIC (ГЛАВНЫЙ ФИКС!)
# Время: 3-5 минут
# Если проблема в mosaic, метрики должны вырасти > 0

experiment_name: "fix_a_no_mosaic"

# ========== ОСНОВНЫЕ ПАРАМЕТРЫ ==========
model: "yolov8s.pt"
epochs: 30      # Быстрый тест
imgsz: 1920     # Объекты будут 8.5×18.2 px (на грани, но видимы)
batch: 1

# ========== ОПТИМИЗАТОР ==========
optimizer: "auto"
lr0: 0.001      # Снижено с 0.002 (более стабильно)
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# ========== АУГМЕНТАЦИИ ==========
# КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: ОТКЛЮЧЁН MOSAIC!
mosaic: 0.0     # ← БЫЛ 1.0 - ЭТО ГЛАВНЫЙ ФИКС!
degrees: 0.0
translate: 0.0
scale: 0.0
fliplr: 0.5     # Оставляем для вариативности
flipud: 0.0
shear: 0.0

# ========== ЦВЕТОВЫЕ АУГМЕНТАЦИИ ==========
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.4

# ========== ПОТЕРИ (LOSS) ==========
# Увеличены для лучшей локализации и классификации
box: 10.0       # Было 7.5 (больше фокуса на bbox)
cls: 1.0        # Было 0.5 (больше фокуса на классификации)
dfl: 1.5

# ========== РЕГУЛЯРИЗАЦИЯ ==========
dropout: 0.0
mixup: 0.0
copy_paste: 0.0

# ========== ДРУГИЕ ПАРАМЕТРЫ ==========
patience: 50
close_mosaic: 10    # Не важно т.к. mosaic=0
warmup_epochs: 3.0
cos_lr: False

# ========== ТЕСТИРОВАНИЕ ==========
conf_threshold: 0.001
iou_threshold: 0.45
grayscale: false

# ========== ОЖИДАЕМЫЙ РЕЗУЛЬТАТ ==========
# Если mosaic была проблема:
# - mAP50 должно вырасти > 0 (было 0)
# - cls_loss должен снизиться < 20 (был 40+)
# - confidence должен вырасти > 0.3 (был 0.22)
#
# Если mAP всё ещё = 0:
# - Проблема не только в mosaic
# - Попробуйте train_config_FIX_B.yaml (imgsz=2560)
