# Конфигурация для экспериментов с обучением YOLO
# Скопируйте этот файл и создайте варианты (train_config_v2.yaml и т.д.)

# Название эксперимента (будет использовано в name)
experiment_name: "baseline"

# ========== ОСНОВНЫЕ ПАРАМЕТРЫ ==========
model: "yolov8s.pt"  # YOLOv8 - более стабильная архитектура
epochs: 50  # Увеличено для мелких объектов
# imgsz: 416  # Компромисс между размером и скоростью (объекты ~9x19px)
imgsz: 920  # Компромисс между размером и скоростью (объекты ~9x19px)
batch: 1     # Уменьшен для больших изображений

# ========== ОПТИМИЗАТОР ==========
optimizer: "auto"  # auto, SGD, Adam, AdamW
lr0: 0.002        # Начальная скорость обучения: 0.001, 0.002, 0.01
lrf: 0.01         # Финальная скорость обучения (множитель): 0.01, 0.1
momentum: 0.937   # Momentum для SGD: 0.9, 0.937, 0.95
weight_decay: 0.0005  # L2 регуляризация: 0.0001, 0.0005, 0.001

# ========== ГЕОМЕТРИЧЕСКИЕ АУГМЕНТАЦИИ ==========
# ✅ Включены для работы с 1 изображением
mosaic: 1.0      # Мозаика (склейка 4 изображений): помогает при малом датасете
degrees: 0.0     # Вращение: 0.0 (отключено для схем)
translate: 0.0   # Сдвиг: 0.0
scale: 0.0       # Масштабирование: 0.0
fliplr: 0.5      # Горизонтальный flip: увеличивает вариативность
flipud: 0.0      # Вертикальный flip: 0.0 (схемы не переворачиваем)
shear: 0.0       # Сдвиг: 0.0

# ========== ЦВЕТОВЫЕ АУГМЕНТАЦИИ ==========
# ✅ Для схем полезны умеренные значения
hsv_h: 0.015     # Hue (оттенок): 0.0, 0.015, 0.05
hsv_s: 0.5       # Saturation (насыщенность): 0.3, 0.5, 0.7
hsv_v: 0.4       # Value (яркость): 0.2, 0.4, 0.6

# ========== DROPOUT И РЕГУЛЯРИЗАЦИЯ ==========
dropout: 0.0     # Dropout: 0.0, 0.1, 0.2
mixup: 0.0       # MixUp аугментация: 0.0, 0.15
copy_paste: 0.0  # Copy-paste аугментация: 0.0, 0.5

# ========== ПОТЕРИ (LOSS) ==========
box: 7.5         # Вес box loss: 5.0, 7.5, 10.0
cls: 0.5         # Вес classification loss: 0.3, 0.5, 1.0
dfl: 1.5         # Вес distribution focal loss: 1.0, 1.5, 2.0

# ========== ДРУГИЕ ПАРАМЕТРЫ ==========
patience: 50     # Early stopping: 20, 50, 100
close_mosaic: 10 # Отключить мозаику за N эпох до конца
warmup_epochs: 3.0  # Warmup эпохи: 1.0, 3.0, 5.0
cos_lr: False    # Косинусное расписание LR: False, True

# ========== ТЕСТИРОВАНИЕ ==========
conf_threshold: 0.001  # Порог уверенности для тестирования: 0.05, 0.1, 0.25
iou_threshold: 0.45  # Порог IoU для NMS: 0.3, 0.45, 0.6
grayscale: false  # Конвертировать в черно-белое: true, false

# ========== РЕКОМЕНДАЦИИ ПО ЭКСПЕРИМЕНТАМ ==========
#
# Для улучшения детекции попробуйте:
#
# 1. УВЕЛИЧИТЬ РАЗМЕР МОДЕЛИ:
#    model: "yolo11s.pt"  # Вместо yolo11n.pt
#
# 2. УВЕЛИЧИТЬ РАЗМЕР ИЗОБРАЖЕНИЯ:
#    imgsz: 1536  # Вместо 1280
#
# 3. НАСТРОИТЬ СКОРОСТЬ ОБУЧЕНИЯ:
#    lr0: 0.001  # Меньше = стабильнее
#    lrf: 0.1    # Больше = меньше затухание
#
# 4. УВЕЛИЧИТЬ КОЛИЧЕСТВО ЭПОХ:
#    epochs: 300
#
# 5. НАСТРОИТЬ ВЕСА ПОТЕРЬ:
#    box: 10.0   # Больше фокуса на точности bbox
#    cls: 1.0    # Больше фокуса на классификации
#
# 6. ДОБАВИТЬ РЕГУЛЯРИЗАЦИЮ:
#    dropout: 0.1
#    weight_decay: 0.001
#
# 7. ДЛЯ МЕЛКИХ ОБЪЕКТОВ:
#    imgsz: 1536
#    mosaic: 0.0
#    scale: 0.0
