# FIX B: АГРЕССИВНОЕ УВЕЛИЧЕНИЕ
# Время: 10-20 минут (медленно на CPU)
# Используйте если FIX A не помог

experiment_name: "fix_b_large_size"

# ========== ОСНОВНЫЕ ПАРАМЕТРЫ ==========
model: "yolov8m.pt"  # Более мощная модель (22M параметров vs 11M)
epochs: 50           # Больше чем FIX A
imgsz: 2560          # Объекты будут ~11×23 px (больше шансов)
batch: 1

# ========== ОПТИМИЗАТОР ==========
optimizer: "auto"
lr0: 0.0005     # Ещё меньше для стабильности
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# ========== АУГМЕНТАЦИИ ==========
mosaic: 0.0     # ОТКЛЮЧЁН!
degrees: 0.0
translate: 0.0
scale: 0.0
fliplr: 0.5
flipud: 0.0
shear: 0.0

# ========== ЦВЕТОВЫЕ АУГМЕНТАЦИИ ==========
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.4

# ========== ПОТЕРИ (LOSS) ==========
# Максимальный фокус на локализации
box: 15.0       # Максимум!
cls: 2.0        # Увеличено для классификации
dfl: 1.5

# ========== РЕГУЛЯРИЗАЦИЯ ==========
dropout: 0.0
mixup: 0.0
copy_paste: 0.0

# ========== ДРУГИЕ ПАРАМЕТРЫ ==========
patience: 50
close_mosaic: 10
warmup_epochs: 5.0  # Больше warmup для большой модели
cos_lr: False

# ========== ТЕСТИРОВАНИЕ ==========
conf_threshold: 0.001
iou_threshold: 0.45
grayscale: false

# ========== ПРЕДУПРЕЖДЕНИЕ ==========
# ВНИМАНИЕ: imgsz=2560 ОЧЕНЬ МЕДЛЕННО на CPU!
# Ожидайте 20-30 секунд на эпоху (50 эпох = 15-25 минут)
#
# Если слишком медленно:
# - Уменьшите epochs до 30
# - Или используйте GPU
# - Или попробуйте вариант C (crops из DIAGNOSIS_REPORT.md)
