# КОНФИГУРАЦИЯ ДЛЯ TRAIN_00.JPG (CROP)
# ДООБУЧЕНИЕ: Увеличиваем epochs и усиливаем loss weights

experiment_name: "crop_extended"

# ========== ОСНОВНЫЕ ПАРАМЕТРЫ ==========
model: "yolov8s.pt"
epochs: 500     # Увеличено с 30 для лучшего обучения
# epochs: 200     # Увеличено с 30 для лучшего обучения
imgsz: 640      # ← ИДЕАЛЬНО для train_00 (758×564px)
                # Объекты будут ~17×38 px - ОТЛИЧНО ВИДИМЫ!
batch: 1

# ========== ОПТИМИЗАТОР ==========
optimizer: "auto"
lr0: 0.0005     # Снижено с 0.001 для стабильности
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# ========== АУГМЕНТАЦИИ ==========
# КЛЮЧЕВОЕ: MOSAIC ОТКЛЮЧЁН!
mosaic: 0.0     # ← ГЛАВНЫЙ ФИКС! (был 1.0)
degrees: 0.0
translate: 0.0
scale: 0.0
fliplr: 0.5     # Оставляем для вариативности
flipud: 0.0
shear: 0.0

# ========== ЦВЕТОВЫЕ АУГМЕНТАЦИИ ==========
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.4

# ========== ПОТЕРИ (LOSS) ==========
box: 15.0       # Максимальный фокус на локализации
cls: 2.0        # Увеличенный фокус на классификации
dfl: 1.5

# ========== РЕГУЛЯРИЗАЦИЯ ==========
dropout: 0.0
mixup: 0.0
copy_paste: 0.0

# ========== ДРУГИЕ ПАРАМЕТРЫ ==========
patience: 50
close_mosaic: 10
warmup_epochs: 3.0
cos_lr: False

# ========== ТЕСТИРОВАНИЕ ==========
conf_threshold: 0.25  # Оптимальный порог (было 0.001 - создавало хаос!)
iou_threshold: 0.45
grayscale: false

# ========== ОЖИДАЕМЫЙ РЕЗУЛЬТАТ ==========
# ДООБУЧЕНИЕ (100 epochs vs 30):
# Первые 30 эпох: mAP50=0.28, max_conf=0.15
#
# После 100 эпох ожидаем:
# - mAP50 > 0.5-0.7
# - confidence > 0.4-0.6
# - cls_loss < 2.0 (было 3.8)
# - Меньше false positives
